# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3219e324c32a141c41cb92b8ca5c5482f264067e6d01d50ed54fb2b962b3dac15557e0f11f3a3df28a869da536fd413501d68dc146a91997dea0fb915e3f4a27

test:
  secret_key_base: 1992cbc58c1623620d6dba5a7078b8599729e5c833e8b377e068975b82d4b1048aca19ab46bc30dcc1604a7292c7f9fdd2f1f712f4a650842affb980cbada573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
